name: FACEBOOK IMAGE SCHEDULER

on:
  workflow_dispatch:
  # schedule:
  #    - cron: '0 */3 * * *'
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            FACEBOOK/
            requirements.txt
          fetch-depth: 1

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'  # Specify the Python version you need

      # Install the necessary packages
      - name: Installed package list
        run: apt list --installed

      # Install dependencies
      - name: Install dependencies
        run: |
         python3 -m pip install --upgrade pip
         pip3 install -r requirements.txt

      # Run your Python script
      - name: Run Python script
        env:
            APP_ID: ${{ secrets.APP_ID }}
            APP_SECRET: ${{ secrets.APP_SECRET }}
            API_VERSION: ${{ secrets.API_VERSION }}
            FACEBOOK_ACCOUNT_ID: ${{ secrets.FACEBOOK_ACCOUNT_ID }}
            FACEBOOK_BASE_URL: ${{ secrets.FACEBOOK_BASE_URL }}
            FACEBOOK_ACCESS_TOKEN: ${{ secrets.FACEBOOK_ACCESS_TOKEN }}
            RENDER_BASE_IMAGE_URL: ${{ secrets.RENDER_BASE_IMAGE_URL }}
            RENDER_BASE_VIDEO_URL: ${{ secrets.RENDER_BASE_VIDEO_URL }}
            GEMINI_IMAGE_VIDEO_CAPTION_KEY: ${{ secrets.GEMINI_IMAGE_VIDEO_CAPTION_KEY }}
            GEMINI_FACEBOOK_TEXT_KEY: ${{ secrets.GEMINI_FACEBOOK_TEXT_KEY }}
        run: python3 FACEBOOK/facebook_page_image.py
